---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_paths:
    - spec/
    - Guardfile
ratings:
  paths:
  - "lib/**.rb"
exclude_paths:
- spec/
- Guardfile