# appveyor.yml

version: "{build}"

install:
  - ps: ((New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt', "$env:TMP\ca-bundle.crt"))
  - SET SSL_CERT_FILE=%TMP%\ca-bundle.crt
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - set PATH=C:\Program Files\Java\jdk1.8.0;%PATH%
  - echo %PATH%
  - bundle install

build: off

environment:
  matrix:
    - ruby_version: '22'
    - ruby_version: 22-x64
    - ruby_version: '23'
    - ruby_version: 23-x64

branches:
  only:
    - master

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - ping www.spigotmc.org
  - ping dev.bukkit.org
  - ping www.curse.com
  - ping hub.spigotmc.org

test_script:
  - bundle exec rake
