#!/usr/bin/env ruby

require 'spigoter'
require 'trollop'


opts = Trollop::options do
    banner <<-EOS
Spigoter, a command line utity for minecraft servers.

Usage:
       spigoter [options]
where [options] are:
EOS
    opt :javaparm, 'Sets the java parameters', :default => '-jar -Xmx...?' #TODO: Poner esto aqui
	opt :compile, "Compiles spigot and sets the new version", :default => 'lastest'
	opt :update, "Set permissons plugin", :default => 'all'
end

puts opts